message:
  topic: 
    name: mytopic
greeting:
  topic:
    name: greeting
filtered:
  topic:
    name: filtered
partitioned:
  topic:
    name: partitioned
kafka:
  bootstrapAddress: localhost:8080

spring:
  profiles:
    active: local
  #Kafka
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group-id-oing
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
# Kafka Topic
#demo:
#  kafka:
#    topic:
#      # Batch 1
#      topic-1: batch1
#      topic-2: batch2
#      topic-3: batch3
#      topic-4: batch4
#    bootstrapAddress: localhost:9092
    
      
      