message:
  topic: 
    name: mytopic
greeting:
  topic:
    name: greeting
filtered:
  topic:
    name: filtered
partitioned:
  topic:
    name: partitioned
kafka:
  bootstrapAddress: localhost:9092

spring:
  profiles:
    active: local
  #Kafka
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group-id-oing
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
# Kafka Topic
#demo:
#  kafka:
#    topic:
#      # Batch 1
#      topic-1: batch1
#      topic-2: batch2
#      topic-3: batch3
#      topic-4: batch4
#    bootstrapAddress: localhost:9092
    
# DB - postgresql
# spring.demo.datasource.driver-class-name=org.postgresql.Driver
# spring.demo.datasource.jdbc-url=jdbc:postgresql://10.47.36.66:5432/postgres
# spring.demo.datasource.username=postgres
# spring.demo.datasource.password=postgres

#logback
# logging.level.org.geopaas.api=debug
#logging.file.name=/NDATA3/platform/logs/api-pip/api-pip.log
#logging.file.max-size=50MB
#logging.file.max-history=10
      
      
